src/rust/api/sqlx-data.json
src/rust/api/src/routes.rs
src/rust/api/src/routes/account.rs
src/rust/api/src/routes/market.rs
src/rust/db/migrations/2023-03-16-025536_create_markets/up.sql
src/rust/db/src/models/market.rs
src/rust/db/src/schema.rs
src/rust/types/src/lib.rs
src/rust/types/src/query.rs

Adds `name` field to `/markets` endpoint so that Next.js can generate URLs that look like `https://econia.exchange/trade/APT-USDC` instead of `https://econia.exchange/trade/123`.

ECO-118: add human readable market name to markets table

---

src/rust/Cargo.lock
src/rust/api/Cargo.toml
src/rust/db/Cargo.toml
src/rust/db/src/lib.rs
src/rust/db/tests/bar_tests.rs
src/rust/db/tests/coin_tests.rs
src/rust/db/tests/helpers.rs
src/rust/db/tests/market_tests.rs
src/rust/db/tests/order_event_tests.rs

Removing feature `config-loader` from db library, since it does not have to be exposed as a feature. It is also unintuitive to have to pass `--features config-loader` every time you want to run a unit test.

db library cleanup

---

src/typescript/frontend/src/pages/trade/[market_name].tsx

this was the only way i could think of to consistently keep a "set" chart height.
Because the chart inherently does not have any height, it's height depended on the limit order component.
to keep the chart a consistent size, added a min height according to spec.
though now I think the page will overflow vertically regularly, so take a look into this w/ kiki
row 28 in bugs spreadsheet

Layout when order switch

---

src/typescript/frontend/src/pages/trade/[market_name].tsx

test at 780px
mimic coinbase overflow when exchange elements don't fit on screen but not narrow enough to proc mobile view

Eco 162: When opening a narrowed down window, the stat bar appears to be cut short to the right.

---

src/typescript/frontend/src/components/icons/ArrowIcon.tsx
src/typescript/frontend/src/contexts/ConnectWalletContext.tsx
src/typescript/frontend/tailwind.config.ts

i believe background blur is already fixed, so just hover for now
super weird behavior that i was struggling to figure out - some tailwind classes were applying and some were not...
fixed it by updating the paths in tailwind config? see: 6ed8e33d2247ea9bf4f98978cad688775da2cf2c
https://stackoverflow.com/a/75428250

Eco 168: Both the Hover & Blur do not match the Figma reference

---

doc/doc-site/docs/move/changelog.md
doc/doc-site/docs/off-chain.md
src/move/econia/sources/incentives.move
src/move/econia/sources/market.move
src/move/econia/sources/registry.move
src/move/econia/sources/user.move

`move-to-ts` is not official Aptos tooling, nor is it maintained by Econia developers.
If devs wish to use `move-to-ts` with Econia, they can always fork the Econia repo and add attributes themselves.

Deprecate move-to-ts attributes

---

src/rust/api/sqlx-data.json
src/rust/api/src/routes.rs
src/rust/api/src/routes/market.rs

Adds `/markets/:market_id/order/:market_order_id` endpoint for retrieving order status of an individual order.

ECO-201: add order status by market and order id endpoint

---

src/python/sdk/econia_sdk/types.py

It looks like this got missed during porting. Let's add it. Value is based on [this reference](https://github.com/econia-labs/econia/blob/main/src/move/econia/sources/market.move#L836).

Add missing `PostOrAbort` to `types.py`

---

src/move/faucet/Move.toml

The faucet does not need all of Econia as a dependency, and this is causing problems. Instead let's just import the aptos-core framework directly.
Tested by publishing it to `0x4334ed72a7037abfd05bb7b846fa4535cc3d2cb31b7565939817de15551a6c03` on devnet.

Add aptos-core to dependencies, remove econia

---

src/python/sdk/econia_sdk/entry/market.py

This function is right now broken. Using it will result in an error: `"Transaction Executed and Committed with Error NUMBER_OF_ARGUMENTS_MISMATCH"` due to the inclusion of an erroneous size argument (likely a victim of copy/paste here). Let's get rid of it.
I tested this by calling the function in a separate script I'm working on, and it works--the error is cleared.

Remove extra arg in place_limit_order_user_entry

---

src/typescript/frontend/src/components/DepthChart.tsx
src/typescript/frontend/src/components/trade/TVChartContainer.tsx
src/typescript/frontend/src/pages/trade/[market_name].tsx
src/typescript/frontend/tailwind.config.ts

Also fixes the layout shift that used to occur while the site was waiting for TradingView to load.

ECO-227: Hide depth chart when viewing on short screen

---

doc/doc-site/docs/move/changelog.md
src/move/econia/doc/market.md
src/move/econia/doc/user.md
src/move/econia/sources/market.move
src/move/econia/sources/user.move

Previously, if a `NO_RESTRICTION` limit order fully filled across the spread, it would emit a `CancelOrderEvent` with `CANCEL_REASON_TOO_SMALL_AFTER_MATCHING`.
Now, if a `NO_RESTRICTION` limit order fills across the spread it will not emit a `CancelOrderEvent` for a full fill. If it takes all liquidity but the remaining size is not big enough to post, it will emit a `CancelOrderEvent` with reason `CANCEL_REASON_TOO_SMALL_AFTER_MATCHING`.
Now, cancel event behavior is consistent across limit orders, market orders, and swap orders. If an order fully fills during the transaction in which it was placed, it will emit A `Place<Limit | Market | Swap>OrderEvent` and `FillEvent`(s), but not a `CancelOrderEvent`.
Move source code has been tested to 100% coverage, but there is no way to validate …

Remove cancel event for limit order when all size fills

---

src/typescript/frontend/src/components/Page.tsx
src/typescript/frontend/src/pages/faucet/index.tsx

changes:
- faucet page match figma
- remove hardcoded positioning, centered vertically but updated `Page` with `h-screen` as `h-full` in child does not work if parent's height is set with `min-height`
- added default faucet wallet value if `undefined` or `null` to 0
screenshot:

ECO-237: faucet page match figma + default faucet wallet value

---

doc/doc-site/docs/move/changelog.md
src/move/econia/doc/user.md
src/move/econia/sources/user.move

Like #347 , the change in this PR would ideally have been included in #321 , but it was overlooked because the Move unit testing framework at the time did not include event assertion. The functionality addressed in this PR was uncovered while writing end-to-end testing functionality.
Now that https://github.com/aptos-labs/aptos-core/pull/9181 is available, it is suggested that all event cases be tested in a unit testing context.

[ECO-256] Correct equality comparator for internal cancel event logic

---

src/python/sdk/econia_sdk/types.py

This constant is being added soon. Let's add it in parallel. We're missing `8` because I believe it's no longer in use.

[ECO-272] Add the new constant to the enum

---

doc/doc-site/README.md

They are currently using yarn and should be using pnpm. In addition, the corrected steps for running should be:
pnpm install
pnpm start

[ECO-270] Change README for docs-site

---

src/typescript/frontend/src/contexts/AptosContext.tsx

did some snooping their codebase and didn't find any references for the option `checkSuccess` (though it does show up in intellisense as a type).
Regardless, they had an example for error handling that I ported over
https://github.com/aptos-labs/aptos-wallet-adapter/tree/main/packages/wallet-adapter-react#signandsubmittransactionpayload

ECO-144: frontend toast when tx fail

---

src/python/sdk/econia_sdk/view/user.py

This getter doesn't appear to exist in the `user` module, so let's remove it from the SDK. This is used elsewhere in our codebase so I'm not sure how it got in, must have been an old version of a diff that got revised.
Link to constant getters:
https://github.com/econia-labs/econia/blob/main/src/move/econia/sources/user.move#L86-L97

Remove get_CANCEL_REASON_TOO_SMALL_AFTER_MATCHING

---

src/typescript/frontend/src/components/trade/OrdersTable.tsx
src/typescript/frontend/src/pages/trade/[market_name].tsx

Adds
- Sorting by column when clicking header of orders table
- Overflow on y-axis when there are too many order rows to fit inside the table height
Notes
- It seems like there are no easy solutions for adding a border on the bottom of the table header that does not scroll with the body? I ended up adding a pseudoelement on the `<tr>` element inside `<thead>`, but open to suggestions for better solutions
- Need some icons for sorting direction indicators. I've put in some unicode characters as placeholders, but this shouldn't be the final version
- Should order statuses other than "open" be color coded? Figma only shows this variant.

ECO-133: Add sorting to orders table, overflow when order rows do not fit

---

src/typescript/frontend/src/components/trade/OrderEntry/LimitOrderEntry.tsx

ECO-261 REQUIRED text positioning

---

doc/doc-site/docs/move/changelog.md
doc/doc-site/docs/off-chain/events.md
src/move/econia/Move.toml
src/move/econia/doc/market.md
src/move/econia/doc/user.md
src/move/econia/sources/market.move
src/move/econia/sources/registry.move
src/move/econia/sources/user.move

#321 and several associated follow up PRs added comprehensive event emissions for market events like `PlaceLimitOrderEvent`. At the time, however, event emissions could not verified using the Move unit testing framework, and several minor issues were uncovered through discussions/manual testing:
* #347
* #360
Aptos Labs recently enabled unit testing of events in Move via https://github.com/aptos-labs/aptos-core/pull/9181, and as such this PR updates the Move unit testing suite to test event emissions.
Before this PR, Move code was already tested to 100% coverage, and as such this PR simply adds event assert statements to the existing coverage suite where applicable. Notably, this includes all non-expected-failure tests listed under the doc comments for:
* `market::match()`
* …

[ECO-247] Add event emission unit tests, with uncovered cancel reasons

---

src/python/sdk/.gitignore
src/python/sdk/.vscode/settings.json
src/python/sdk/README.md
src/python/sdk/econia_sdk/view/registry.py
src/python/sdk/mypy.ini
src/python/sdk/poetry.lock
src/python/sdk/pyproject.toml

One thing to consider: black defaults to 88 character lines.
They lay out their reasoning here, and I would favor sticking to it, but are 80 character lines important enough to anyone here that they feel it is worth overriding this setting?
<https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#line-length>

General housekeeping for Python SDK

---

doc/doc-site/docs/move/changelog.md

`MakerEvent` and its associated handle were deprecated per #321. This PR specifies the deprecation in the Move changelog

[ECO-330] Deprecate MakerEvent/handle in changelog

---

doc/doc-site/docs/off-chain/python-sdk.md
src/python/sdk/econia_sdk/utils/decimals.py
src/python/sdk/pyproject.toml

Multiple people have stumbled across lot size, tick size, and min size and rightly become confused. I've developed here helpers for the Python SDK (as well as documentation) that calculate lot/tick size and min size for the user. I wanted something to help with price without the chance of it being misused or truncation ruining someone's day so I provided a helper to determine the minimum quote per lot, that is price granularity.

[ECO-279] Develop decimal guidance

---

doc/doc-site/docs/off-chain/python-sdk.md
src/python/sdk/examples/trade.py

We need to fix the headings (caps first letter) and change language (set-up -> setup) to be more consistent with the rest of the docs site,

[ECO-332] Make python SDK docs more consistent

---

src/rust/db/src/models/order.rs
src/rust/types/src/events.rs

This PR adds to Rust enums cancel reasons that were uncovered during event emission unit testing per #366

[ECO-347] Add missing cancel reasons to Rust

---

src/typescript/frontend/src/components/trade/DepositWithdrawModal/DepositWithdrawContent.tsx
src/typescript/frontend/src/components/trade/OrderEntry/LimitOrderEntry.tsx
src/typescript/frontend/src/components/trade/OrderEntry/MarketOrderEntry.tsx
src/typescript/frontend/src/utils/coin.ts
src/typescript/frontend/src/utils/formatter.ts

Suggested changes for #393.
- Checks for missing values at the very beginning to avoid usage of optional chaining and null coalescing later on
- Moves return statements to the earliest point they can be called, preventing unnecessary calculations
- Reduces the number of conversions, especially to bigint, necessary to perform these validations
- Fixes number of decimal places for checking quote balance on limit bid orders

[ECO-137 - ECO-141] Order validation logic changes

---

doc/doc-site/docs/overview/orders.md

I've removed the math which is kind of distracting in favor of using the new Python helpers with a link to their implementation for the curious.
The rest of the sections are honestly fine in my opinion. Usage of Python to calculate things is fine, it was the Latex that was distracting.

[ECO-245] Edit orders documentation a bit

---

src/rust/Cargo.lock
src/rust/Cargo.toml

Moved `sdk` from `exclude` to `members` in workspace's (`Cargo.toml`
Also add two patches to Cargo.toml:
- x25519-dalek to fix double dependency issue
- meriln to fix borrowing issue
Both these are also in Aptos' Cargo.toml.

[ECO-371] Add every package to the main workspace

---

doc/doc-site/docs/move/changelog.md
src/move/econia/Move.toml
src/move/econia/doc/incentives.md
src/move/econia/doc/market.md
src/move/econia/sources/incentives.move
src/move/econia/sources/market.move
src/move/econia/sources/registry.move
src/move/econia/sources/user.move

@chen-robert
This PR removes unnecessary mutable borrows in view functions.
Note that https://github.com/aptos-labs/aptos-core/pull/9369 changed an event unit testing function signature, and so tests are updated here to enable a test run.
All tests pass.

[ECO-378] Remove unnecessary mutable borrows in view funcs

---

doc/doc-site/docs/move/changelog.md
src/move/econia/Move.toml
src/move/econia/doc/market.md
src/move/econia/sources/market.move

@chen-robert
This PR adds a check for an order's price field against its corresponding AVL queue insertion key, during price level computation.
A failure test is included.
This PR is branched from #428, and should be merged after it merges

[ECO-379] Check order price field against lookup key

---

src/rust/Cargo.lock
src/rust/Cargo.toml
src/rust/sdk/example/Cargo.toml
src/rust/sdk/example/src/main.rs
src/rust/sdk/src/lib.rs
src/rust/types/src/events.rs

- Fix import and parentheses warnings.
- Fix cargo workspaces configuration.

[ECO-419] Fix cargo workspace config and rust warnings

---

doc/doc-site/docs/off-chain/python-sdk.md
doc/doc-site/docs/overview/orders.md
src/python/sdk/econia_sdk/utils/decimals.py
src/python/sdk/pyproject.toml

Clients would like helpers for calculating a tick size given a desired price granularity (and other configuration variables). They would also like helpers for converting between decimal price and integer price since this can be confusing. Here I've added those helpers as well as included blurbs about the new tick size helper in our documentation.

[ECO-384] Add new decimal helpers to Python SDK

---

src/python/sdk/examples/trade.py
src/python/sdk/pyproject.toml

Right now the parameters are kind of wonky because they were made before we had helpers to go around the tick size intermediary value. Here I've used the `get_market_parameters_integer` helper with a size precision of "0.001" and a price precision of "0.001" along with base decimals 8 and quote decimals 6.
I've run the script through and confirmed it still works with existing values.

[ECO-456] Update market parameters in trade.py

---

src/rust/Cargo.lock
src/rust/Cargo.toml

We have added this submodule so that it can be extended with our processor code. However, we have to integrate the various projects within the imported workspace into ours. This will allow it to utilize our types. We have to essentially take over as the workspace for the projects which means adding a bunch of dependencies to our workspace which is probably fine.
I had to be careful because we also have to use the same features, such as `serde_json` now having ordered fields presumably for consistent hashing and such in some code of the processors.
Their workspace Cargo.toml: https://github.com/econia-labs/aptos-indexer-processors/blob/main/rust/Cargo.toml
Processor Cargo.toml: https://github.com/econia-labs/aptos-indexer-processors/blob/main/rust/processor/Cargo.toml
Server-Framework …

[ECO-454] Integrate aptos-indexer-processors/processor

---

src/rust/Cargo.lock
src/rust/Cargo.toml
src/rust/dbv2/migrations/2023-08-25-111710_add_market_registration_events/down.sql
src/rust/dbv2/migrations/2023-08-25-111710_add_market_registration_events/up.sql
src/rust/dbv2/src/lib.rs
src/rust/dbv2/src/models.rs
src/rust/dbv2/src/schema.rs

This is the humble beginnings of our chain data processor that will put Econia's events in a database. We've started with market registration here and I've done my best to keep things at an absolute minimum.
I had to update our table migration to use a more practical primary key schema as recommended by Aptos, and added a few other things required by the processor. I've only added what the processor would not run without (trial-by-error).

[ECO-413] Add V2 market registration processor

---

src/docker/compose.dss-local.yaml

Right now our docker compose file uses the `postgres` role which doesn't exist in the database. We should be using the `anon` role which was created in a recent commit. This commit updates the role to that and also updates the processor submodule commit to the latest.

[ECO-475][Bug] Fix postgrest role

---

src/typescript/frontend/src/pages/trade/[market_name].tsx

I think I fixed it, I can't seem to reproduce the error now.
Would like to get some opinions on the current fix -- seems hacky as we need to check websocket status everytime we want to send a message.
But we have to do this because websocket functions are async and when `onopen` is called the websocket reference could be stale. Even though ryosuke mentioned that hooks are called twice in dev mode, this problem occurred in prod.
Additionally, we are properly cleaning up the websocket anyways so I'm not entirely sure why the `onopen` could be called after we close the websocket. see: https://github.com/econia-labs/econia/blob/0d18abfe9cb0f3aab5c0875859480f4e94f3e124/src/typescript/frontend/src/pages/trade/%5Bmarket_name%5D.tsx#L83C5-L83C5

ECO-248: fix websocket connect issue

---

.github/workflows/rust-ci.yml
src/rust/Cargo.lock
src/rust/Cargo.toml

This PR is intended to remove the processor from the cargo workspace to fix CI. It also reviled another problem with CI (an argument to a command that was copy pasted where it shouldn't have been) which was fixed.

[ECO-481] Remove processor from cargo workspace

---

src/rust/dbv2/migrations/2023-08-25-111710_add_market_registration_events/down.sql
src/rust/dbv2/migrations/2023-08-25-111710_add_market_registration_events/up.sql
src/rust/dbv2/src/models.rs
src/rust/dbv2/src/schema.rs

This diff adds the necessary tables and structures to support insertion of place/cancel limit order events in the processor downstream.

[ECO-482] add place/cancel limit order events

---

src/move/econia/Move.toml
src/move/econia/sources/market.move
src/move/econia/sources/user.move
src/move/faucet/Move.toml
src/move/faucet/sources/faucet.move
src/move/testnet-competition-throttler/Move.toml
src/move/testnet-competition-throttler/README.md
src/move/testnet-competition-throttler/sources/throttle.move

This PR adds a testnet trading competition throttler that can be upgradeably inserted and removed from the Econia and Econia faucet packages.

[ECO-498] Implement testnet competition throttling

---

src/move/testnet-competition-throttler/sources/throttle.move

This PR fixes an arithmetic error and adds a view function to the testnet competition throttler

[ECO-490] Tweak throttler arithmetic, add view func

---

doc/doc-site/docs/off-chain/events.md

This PR fixes a link that linked to the wrong module DocGen file

[ECO-488] Fix place swap order event link

---

src/move/econia/sources/user.move

This PR exempts throttling for internal deposits, where the matching engine deposits coins into a user's market account

[ECO-517] Exempt throttling for internal deposits

---

doc/doc-site/docs/move/changelog.md
src/move/econia/Move.toml
src/move/econia/doc/market.md
src/move/econia/sources/market.move

This PR adds a single assert statement to verify that an order size change operation results in an open order above the minimum size for the market

[ECO-557] Abort for size change below min size

---

doc/doc-site/docs/move/changelog.md
src/move/econia/doc/market.md
src/move/econia/sources/market.move

The matching engine returns silently if it encounters an order of size 0, which should never happen in production.
Add an extra check to evict an order of size 0 if one ends up on the book, rather than returning silently. Also add an associated test.

[ECO-562] Evict empty orders during matching

---

src/docker/compose.database.yaml
src/docker/compose.dss-global.yaml
src/docker/database/Dockerfile.postgres
src/rust/dbv2/migrations/2023-09-20-193413_add_limit_order_events/up.sql

Some bugs were found when running the stack in global mode, as well as when running it after running `docker volume prune -af`. Here are the fixes:
- Add `HEALTHCHECK` to the `postgres` service to avoid the `diesel` service from failing due to the `postgres` service not being ready.
- Update `compose.dss-global.yaml`'s `ws` service with the environment variables from `compose.dss-local.yaml`.
- Fix a typo in the `src/rust/dbv2/migrations/2023-09-20-193413_add_limit_order_events/up.sql` file which made WebSockets events for some events not work.

Fix docker compose and sql error

---

src/docker/processor/config-template-global.yaml

The token in `config-template-global.yaml` is similar to a valid token and could be less ambiguous.
Update the auth token to be clearly bogus

[ECO-566] Disambiguate invalid token in config

---

doc/doc-site/docs/off-chain/dss/rest-api.md
doc/doc-site/docusaurus.config.js

* Embed the DSS REST API directly in the docs site topic page
* Remove theme overriding so that link colors are consitent with the rest of the docs site

[ECO-567] Embed DSS REST API in docs site

---

src/rust/Cargo.lock
src/rust/Cargo.toml
src/rust/e2e/Cargo.toml
src/rust/e2e/e2e-proc-macro/Cargo.toml
src/rust/e2e/e2e-proc-macro/src/lib.rs
src/rust/e2e/metadata/Cargo.toml
src/rust/e2e/metadata/src/lib.rs
src/rust/e2e/src/main.rs
src/rust/e2e/src/market_registration.rs
src/rust/e2e/src/utils.rs

Add an e2e framework.
There are 3 crates added in this PR:
| Name  | Description |
| --- | --- |
| `e2e` | The main crate. Contains the different tests as well as the main function that runs all those tests.|
| `e2e-proc-macro` | A crate that contains the `e2e_test` proc macro. This macro transforms the return type of a function by wrapping it into `Metadata`. It can also accept a namespace as an argument (this is used to group tests into named spaces). |
| `metadata` | A crate containing a simple `Metadata` struct. This contains the name of the function, as well as the namespace of the test. |
To create a new test, you can look at `e2e/src/market_registration.rs` for inspiration.

[ECO-521] Add e2e framework

---

src/docker/api/Dockerfile.ws

* Fix Haskell compilation to be official, from source, without hacks
* Remove `aptos-core` submodule

[ECO-618] Fix Haskell compile, remove aptos-core

---

src/docker/compose.dss.yaml
src/rust/aggregator/README.md
src/rust/aggregator/src/data/user_history.rs
src/rust/dbv2/migrations/2023-09-04-113144_postgrest/up.sql

This PR adds assorted tweaks to #518:
* Update JWT secret per https://github.com/econia-labs/econia/pull/518#discussion_r1347628232
* Add link to SQLx docs
* Switch magic number to constant

[ECO-616] Add assorted order book PR tweaks

---

doc/doc-site/docs/off-chain/dss/data-service-stack.md
doc/doc-site/docs/off-chain/dss/websocket.md
doc/doc-site/docs/off-chain/python-sdk.md
src/docker/README.md
src/docker/compose.dss-global.yaml
src/docker/compose.dss-local.yaml
src/rust/dbv2/migrations/2023-09-04-113144_postgrest/up.sql
src/rust/dbv2/src/schema.rs

This cleans up #524
* Add assorted fixes in instructions found while running tutorials
* Update processor submodule to head of `econia` branch (since https://github.com/econia-labs/aptos-indexer-processors/pull/11 has now merged)
* Update port mapping for WebSockets to be enclosed in double quotes per Docker compose file spec: https://docs.docker.com/compose/compose-file/compose-file-v3/#ports
* Add missing `web_anon` drop statement to migrations in order to run `diesel database reset`, which auto-updates `schema.rs`

[ECO-622] Cleanup recognized market PR

---

.github/workflows/deploy-doc-site.yml

Enable manual dispatch for docs build due to recent build failing authentication with CloudFlare
If a glitch comes up during CI we need to be able to manually trigger the build

[ECO-658] Enable manual dispatch for docs build

---

src/rust/dbv2/migrations/2023-10-09-223433_add_enumishes/down.sql
src/rust/dbv2/migrations/2023-10-09-223433_add_enumishes/up.sql

Right now for `api.limit_orders` we say `"bid"` or `"ask"` for the side. For consistency let's also convert the binary `direction` of `api.place_swap_order_events` and `api.place_market_order_events` to `"buy"` or `"sell"`.
Verified by visiting http://localhost:3000/place_swap_order_events and http://localhost:3000/place_market_order_events after running the Python script.

[ECO-625] Create new views with enum buy/sell

---

doc/doc-site/docs/off-chain/dss/websocket.md
src/rust/dbv2/migrations/2023-10-03-070930_add_order_queue/up.sql
src/rust/dbv2/migrations/2023-10-10-171102_drop_update_orders_triggers/down.sql
src/rust/dbv2/migrations/2023-10-10-171102_drop_update_orders_triggers/up.sql

This PR removes the triggers that send notifications on updates to swaps and market orders since semantically these orders do not get updates so this was confusing.
Verified using `trade.py`:
```
(econia-sdk-py3.11) (base) egd@Elliotts-MacBook-Pro sdk % poetry run trade
Enter the minimum order size to (re-)use for the market (enter nothing to default to 500==0.5 APT)
Enter the 0x-prefixed address of an Econia deployment (enter nothing to default to local OR re-run with ECONIA_ADDR environment variable)
Enter the 0x-prefixed private key of the Econia deployment (enter "." to use local OR enter nothing to skip recognizing the market)
Enter the 0x-prefixed address of an Econia faucet deployment (enter nothing to default to local OR re-run with FAUCET_ADDR environment variable)
Enter the URL …
```

[ECO-660] Remove update swap/market order triggers

---

src/rust/aggregator/src/main.rs

* Take out market registration event aggregation, which was a proof of concept, is not necessary at present, and was causing panics

[ECO-683] Remove daily markets aggregation

---

doc/doc-site/docs/off-chain/dss/gcp.md

Add to GCP instructions for limiting the max number of rows allowed in a PostgREST query
1. Checked out #540
1. Updated `compose.dss-core.yaml` environment variables for postgres:
```yaml
environment:
PGRST_DB_URI: "postgres://econia:econia@postgres:5432/econia"
PGRST_DB_ANON_ROLE: web_anon
PGRST_DB_SCHEMA: api
PGRST_DB_MAX_ROWS: 3
```
2. Ran in Econia root:
```
docker ps -aq | xargs docker stop | xargs docker rm
docker volume prune -af
docker image remove postgrest/postgrest
docker compose --file src/docker/compose.dss-global.yaml up
```
4. Ran in `src/rust/dbv2`:
```sh
export DATABASE_URL=postgres://econia:econia@localhost:5432/econia
cp competition-metadata-template.json competition-metadata.json
cargo build --release --bin init-competition
./../target/release/init-competition …
```

[ECO-662] Add PostgREST max rows config step

---

src/rust/dbv2/README.md
src/rust/dbv2/diesel.toml
src/rust/dbv2/migrations/2023-10-06-164142_leaderboards/down.sql
src/rust/dbv2/migrations/2023-10-06-164142_leaderboards/up.sql
src/rust/dbv2/src/bin/add-exclusions.rs
src/rust/dbv2/src/bin/add-inclusions.rs
src/rust/dbv2/src/bin/get-competitions.rs
src/rust/dbv2/src/bin/get-exclusions.rs
src/rust/dbv2/src/bin/init-competition.rs
src/rust/dbv2/src/models.rs
src/rust/dbv2/src/schema/aggregator.rs

* Refactor migrations that would not run due to dependencies broken at current head of https://github.com/econia-labs/econia/pull/531
* Rename `exclusion_metadata` to `exclusion_list`
* Add instructions for generating schemas
* Only store in `aggregator.rs` the autogenerated output of diesel, which wraps in`pub mod` 
* Update processor submodule to commit that fixes broken schema dependencies: https://github.com/econia-labs/aptos-indexer-processors/pull/13

[ECO-708] Refactor migrations/schema, update README

---

src/move/econia/sources/user.move
src/move/testnet-competition-throttler/README.md

Revert `user.move` modifications that implemented market account deposit throttling, update throttler README

[ECO-785] Remove market account deposit throttling

---

src/rust/dbv2/migrations/2023-10-06-164142_leaderboards/up.sql

Aggregator was stuck due to empty `aggergator.competition_indexed_events` being empty when creating a new competition.

[ECO-789] fix stuck aggregator

---

doc/doc-site/docs/off-chain/dss/data-service-stack.md
doc/doc-site/docs/off-chain/dss/websocket.md
src/python/sdk/examples/event.py
src/python/sdk/poetry.lock
src/python/sdk/pyproject.toml

We lost JWT generation support due to compatibility issues. So in the WebSockets example, instead of using the now-gone endpoint for the JWT, let's generate the JWT and have that be an example for others.
Validated by running `event` and `trade` scripts against local deployment.

[ECO-745] JWT support update

---

doc/doc-site/docs/move/changelog.md
doc/doc-site/docs/security.md

* Update Move changelog and security docs pages per recent audit/mainnet governance upgrade

[ECO-558] Bumps docs for audit

---

doc/doc-site/docs/off-chain/dss/rest-api.md
doc/doc-site/docusaurus.config.js
doc/doc-site/package.json
doc/doc-site/pnpm-lock.yaml

The docs site build started failing, apparently due to an issue with the redocusaurus Open API plugin.
After some searching I found an issue that appears related, with a comment flagging how failed builds were a result of people using the redoc/open API plugin: https://github.com/facebook/docusaurus/issues/7398#issuecomment-1125621496
The following comment states how on one day a build passed, then the next day it failed. Similar behavior recently affected the Econia docs site build.
Perfect support for the REST API documentation is not a priority at present, but the docs site does need to be able to be updated.
* Disable `redocusaurus` plugin
* Add message to REST API page about plugin issues
From within /doc/doc-site/ I was able to run `pnpm build` without failure, then `pnpm start` …

[ECO-798] Add quick fix for redocusaurus issue

---

src/move/econia/sources/market.move

Limit orders that post do not get throttled because presently the throttler only checks matches.
Throttle limit orders that post too, by simpling throttling all limit orders.

[ECO-816] Throttle all limit orders

---

src/move/econia/sources/avl_queue.move

* On 2023-10-26, during the testnet trading competition, the `market::get_open_orders_all()` view function began to fail with `EXECUTION_LIMIT_REACHED`:
```
~ % aptos move view --function-id $econia_addr::market::get_open_orders_all --args u64:3 --url "https://fullnode.testnet.aptoslabs.com" 
{
"Error": "API error: API error Error(InvalidInput): Failed to execute function: VMError { major_status: EXECUTION_LIMIT_REACHED, sub_status: None, message: None, exec_state: None, location: Module(ModuleId { address: c0de11113b427d35ece1d8991865a941c0578b0f349acabbe9753863c24109ff, name: Identifier(\"avl_queue\") }), indices: [], offsets: [(FunctionDefinitionIndex(45), 29)] }"
}
```
* Quries for just the best bid, and for the best bid and ask still worked:
```
(base) ~ % aptos move view …
```

[ECO-818] Lower eviction threshold

---

src/move/econia/sources/avl_queue.move

#569 sought to evict early, but the logic was flawed because there had already been more than `N_NODES_MAX_EVICT` allocated, so the second conditional check on the stack top being null wouldn't have fired
Focus instead on adding pagination for getting open orders, and revert eviction logic changes

[ECO-820] Revert changes from #569

---

src/terraform/leaderboard-backend/main.tf

This is a draft PR stub to track the state of the repo for the competition leaderboard backend. It is a branch from the `competition-dss-v1.0.0` tag, with IP rate limit tuning.
`competition-metadata.json`:
```json
{
"start": "2023-10-25T00:00:00Z",
"end": "2023-11-01T00:00:00Z",
"prize": 5000,
"integrators_required": [
"0x2e51979739db25dc987bd24e1a968e45cca0e0daea7cae9121f68af93e8884c9",
"0xd718181a753f5b759518d9b896018dd7eb3d77d80bf90ba77fffaf678f781929",
"0x69f76d32b0e6b08af826f5f75a7c58e6581d1c6c4ed1a935b121970f65d7436e"
]
}
```
`config.yaml`
```yaml
health_check_port: 8085
server_config:
processor_config:
type: econia_transaction_processor
econia_address: 0xc0de11113b427d35ece1d8991865a941c0578b0f349acabbe9753863c24109ff
postgres_connection_string: …
```

[ECO-804] Deploy competition DSS v1.0.0

---

src/move/econia/sources/market.move

Size changes are not throttled. Therefore a user can place valid order then later change the size to be larger than allowed.
Throttle size changes too.

[ECO-824] Throttle size changes

---

.gitignore
src/terraform/internal-dss/.gitignore
src/terraform/internal-dss/README.md
src/terraform/internal-dss/cloudbuild.aggregator.yaml
src/terraform/internal-dss/cloudbuild.processor.yaml
src/terraform/internal-dss/main.tf
src/terraform/internal-dss/outputs.tf
src/terraform/internal-dss/variables.tf

Create a new Terraform configuration for a DSS to power internal testing of the Econia reference trading frontend.
Update `gitignore` to exclude Terraform cache files.

[ECO-811] Add internal DSS configuration

---

src/rust/aggregator/src/data/user_history.rs

* Update polling history to be 500 ms using named constant instead of magic number
* Abstract out value defined in multiple places to single constant

[ECO-843] Update user history polling to 500 ms

---

doc/doc-site/docs/off-chain/dss/terraform.md
src/terraform/internal-dss/README.md
src/terraform/internal-dss/main.tf
src/terraform/internal-dss/variables.tf

* Set PostgREST max rows to 500
* Update internal DSS README
* Add destroy-time provisioner to get rid of peering, effectively automating the manual process currently described as a "tip" on the Terraform page of the docs site
* Update docs site project creation instructions to make project naming simpler for assorted projects

[ECO-847] Clean up internal Terraform deployment

---

src/rust/Cargo.lock
src/rust/aggregator/Cargo.toml
src/rust/aggregator/src/data.rs
src/rust/aggregator/src/data/leaderboards.rs
src/rust/aggregator/src/data/markets.rs
src/rust/aggregator/src/data/user_history.rs
src/rust/aggregator/src/main.rs

- renamed `Data` to `Pipeline`
- can now pass db url as cli arg
- can now pass an exclusion list or an inclusion list to run processors
The purpose of this PR is so that people can run the aggregator to get data without having to process leaderboards.
I also renamed `Data` to `Pipeline` because it's more accurate, and it was hard to name things with `Data`.

[ECO-726] Add CLI args

---

src/rust/dbv2/migrations/2023-11-02-131654_small-queries/up.sql

* Address comments from https://github.com/econia-labs/econia/pull/582
* Fix `last_fill` and `first_fill` logic
* Remove lot size multipliers
* Change percentage to be a relative amount
* Run through `pgformatter` via format on save

[ECO-852] Make price info query suggestions

---

src/rust/dbv2/migrations/2023-11-02-210244_execution-price-function/down.sql
src/rust/dbv2/migrations/2023-11-02-210244_execution-price-function/up.sql

Add execution price as a [computed field](https://postgrest.org/en/stable/references/api/computed_fields.html) for orders.
The price is calculated as `SUM(size * price) / SUM(size)`.
Also add two indexes to speed up the function.

[ECO-842] Add execution price field

---

src/rust/dbv2/migrations/2023-11-05-131409_user_market_account_balance/down.sql
src/rust/dbv2/migrations/2023-11-05-131409_user_market_account_balance/up.sql

This PR adds the `/rpc/user_balance` endpoint, which returns the user balance for a given user, market and custodian.
---
```http
GET /rpc/user_balance\?market=MARKET_ID\&custodian=CUSTODIAN_ID\&user_address=USER_ADDRESS
```
```json
[
{
"base_total": 201160061618600000,
"base_available": 201159251459200000,
"base_ceiling": 201161211569500000,
"quote_total": 1933878511960591,
"quote_available": 1933803458830544,
"quote_ceiling": 1933931887592552
}
]
```

[ECO-853] add function to get user market account balance

---

src/rust/dbv2/migrations/2023-11-05-120656_direction_as_string/down.sql
src/rust/dbv2/migrations/2023-11-05-120656_direction_as_string/up.sql

This PR updates the `market_orders` and `swap_orders` endpoints to change the
previously boolean field `direction` to text.
---
**Previous response example**:
```json
[
{
"order_id": 387381625547900583936,
"user": "0x6c509ada7a55a622d97e8f9725723460d3e08e02ebd32de1d9038bbc93530192",
"custodian_id": 0,
"direction": true,
"self_matching_behavior": 2,
"created_at": "2023-09-05T20:45:19.88794+00:00",
"last_updated_at": "2023-09-05T20:45:19.88794+00:00",
"integrator": "0xc0de11113b427d35ece1d8991865a941c0578b0f349acabbe9753863c24109ff",
"total_filled": 500,
"remaining_size": 0,
"order_status": "closed",
"order_type": "market"
}
]
```
**Current response example**:
```json
[
{
"order_id": 387381625547900583936,
"user": …
```

[ECO-857] Use buy/sell instead of boolean for orders endpoints

---

src/rust/dbv2/migrations/2023-10-03-070930_add_order_queue/down.sql
src/rust/dbv2/migrations/2023-11-03-102931_lix_last_increase_timestamp/down.sql
src/rust/dbv2/migrations/2023-11-03-102931_lix_last_increase_timestamp/up.sql

Remove decimals from the `last_increase_timestamp` field in `limit_orders`. Also fix an old related migration.

[ECO-826] Remove decimals from last_increase_timestamp

---

src/rust/dbv2/migrations/2023-11-05-124149_recognized_market_endpoint/down.sql
src/rust/dbv2/migrations/2023-11-05-124149_recognized_market_endpoint/up.sql

This PR adds the following endpoints:
- `/markets`
- `/recognized_markets`
You might ask why `/recognized_markets` exists, as you could query them only by
adding `?is_recognized=eq.true` to the first endpoint to get recognized
markets. The reason it that the second endpoint is more performant, as it is
not joining two tables, as would the query mentioned before do.
---
**Output of querying `/markets`**:
```json
[
{
"market_id": 2,
"time": "2023-09-04T15:20:12.12123+00:00",
"base_account_address": "0xc0de11113b427d35ece1d8991865a941c0578b0f349acabbe9753863c24109ff",
"base_module_name": "example_apt",
"base_struct_name": "ExampleAPT",
"base_name_generic": null,
"quote_account_address": "0xc0de11113b427d35ece1d8991865a941c0578b0f349acabbe9753863c24109ff",
"quote_module_name": "example_usdc", …
```

[ECO-858] create `markets` and `recognized_markets` endpoints

---

src/rust/dbv2/migrations/2023-11-06-214605_rename_execution_price/down.sql
src/rust/dbv2/migrations/2023-11-06-214605_rename_execution_price/up.sql

Change the name of the `execution_price` field to `average_execution_price`.

[ECO-875] rename `execution_price` to `average_execution_price`

---

doc/doc-site/docs/security.md

Update security page with references to auxiliary pagination functions added during testnet competition

[ECO-828] Bump audit references for pagination

---

src/rust/dbv2/migrations/2023-11-07-154637_new_orders_endpoint/down.sql
src/rust/dbv2/migrations/2023-11-07-154637_new_orders_endpoint/up.sql

Instead of having `{limit,market,swap}_orders` and `orders`, only have an `orders` endpoint.
This endpoint will return a list of elements which have the fields of all order types, but with the unused ones set to `null`.
---
```http
GET /orders
```
```json
[
{
"order_id": 67470442778538899702552972,
"created_at": "2023-11-05T15:44:13.294947+00:00",
"last_updated_at": null,
"integrator": "0x2e51979739db25dc987bd24e1a968e45cca0e0daea7cae9121f68af93e8884c9",
"total_filled": 0,
"remaining_size": 200000,
"order_status": "open",
"order_type": "limit",
"user": "0xf3ce7187f9a72e9b63146c28dbb00918623ee60aa2a86828d49cc0d4355554a9",
"direction": "bid",
"price": 6540,
"custodian_id": 0,
"self_matching_behavior": 3,
"restriction": 0,
"min_base": null,
"max_base": null,
"min_quote": …
```

[ECO-845] unify all orders endpoints into one

---

src/docker/compose.database.yaml
src/rust/dbv2/migrations/2023-11-08-091936_markets_overview/down.sql
src/rust/dbv2/migrations/2023-11-08-091936_markets_overview/up.sql

Add `price` and `change` fields to the `/markets` endpoint.
---
```http
GET /markets?market_id=eq.3
```
```json
[
{
"registration_time": "2023-09-04T17:09:37.423851+00:00",
"base_account_address": "0xc0de11113b427d35ece1d8991865a941c0578b0f349acabbe9753863c24109ff",
"base_module_name": "example_apt",
"base_struct_name": "ExampleAPT",
"base_name_generic": null,
"quote_account_address": "0xc0de11113b427d35ece1d8991865a941c0578b0f349acabbe9753863c24109ff",
"quote_module_name": "example_usdc",
"quote_struct_name": "ExampleUSDC",
"lot_size": 100000,
"tick_size": 1,
"min_size": 500,
"underwriter_id": 0,
"is_recognized": true,
"last_fill_price_24hr": 7329,
"percent_change_24h": -0.06817562039814562300
}
]
```

[ECO-891] update markets enpoint with more data

---

src/rust/dbv2/migrations/2023-11-10-212305_fix_orders_enpoint/down.sql
src/rust/dbv2/migrations/2023-11-10-212305_fix_orders_enpoint/up.sql

Before this, the join was incorrect. Due to this, sometimes you would get results with `user` being `null`. Not anymore.

[ECO-903] fix api.orders bad join

---

doc/doc-site/docs/off-chain/dss/data-service-stack.md
src/docker/processor/config-template-global.yaml
src/docker/processor/config-template-local.yaml

Per https://github.com/aptos-labs/aptos-indexer-processors/pull/187, enforce 1 concurrent processor task to uphold total order invariant for Econia events/writesets inserted into db via processor

[ECO-905] Enforce 1 concurrent processor task

---

src/terraform/internal-dss/main.tf

Allow public Cloud SQL connections such that for internal development anyone with the Cloud SQL IP address and password can connect

[ECO-915] Allow public Cloud SQL connections

---

src/python/sdk/econia_sdk/view/market.py
src/python/sdk/pyproject.toml

We've added pagination to "get open orders" and "get price levels" so we need to include these functions in the SDK view helpers. I've also included a helper to get a fixed number of orders/price levels that uses the pagination feature. This is a step away from what we've been doing which is to only provide wrappers for the functions and nothing else. However, it's tricky to do the pagination right (have to use the transaction version) so I figured we should just include it as nobody gets hurt.
Validated by calling each paginator in the middle of `trade.py`

[ECO-829] Include pagination in view function helpers

---

doc/doc-site/docs/off-chain/dss/data-service-stack.md

Show examples of complete testnet and mainnet `config.yaml` files on the DSS page

[ECO-935] Document configs on DSS docs page

---

src/rust/aggregator/src/main.rs
src/rust/aggregator/src/pipelines.rs
src/rust/aggregator/src/pipelines/refresh_materialized_view.rs
src/rust/aggregator/src/pipelines/update_materialized_view.rs
src/rust/dbv2/migrations/2023-11-16-103707_market_volume/down.sql
src/rust/dbv2/migrations/2023-11-16-103707_market_volume/up.sql

Added a new aggregator pipeline that is named `UpdateMaterializedView`. This updates the given materialized view every given duration. This will allow easly creating views that can be updated at a set interval with minimal aggregator code.
This PR also adds a materialized view for market volume, min fill, and max fill in the last 24 hours.

[ECO-914] update `/markets` endpoint to include volume, min, and max

---

src/terraform/internal-dss/main.tf

DO NOT expose a database to the public. This is very poor security practice.
Instead, use the Cloud SQL Auth Proxy if you need to connect to a Cloud SQL instance for development.
@alnoki please read the Cloud SQL documentation before proceeding further.
<https://cloud.google.com/sql/docs/postgres/connect-instance-auth-proxy>

Revert #621

---

doc/doc-site/docs/move/changelog.md
doc/doc-site/docs/security.md
src/move/econia/Move.toml
src/move/econia/doc/market.md
src/move/econia/sources/market.move
src/move/econia/sources/user.move

The changes in his PR only affect auxiliary event emission logic. They do not modify core settlement/accounting/etc. logic.
Without this PR, if a limit order fills completely across the spread but there is still liquidity on the book after matching, a cancel event may be emitted with `CANCEL_REASON_MAX_QUOTE_TRADED`, since the check for `still_crosses_spread` is performed regardless of remaining size.
* After optional cross-spread matching for a limit order, only check for `still_crosses_spread` if `remaining_size > 0`
* Add tests validating that no such cancel event is emitted for applicable cases on both sides 
* Bump changelog and `Move.toml` to `v4.2.1`
* Rebuild Move docs
* Update security docs page per new audit
Tested to 100% coverage per 172bf51 and bfaf890

[ECO-937] Patch max quote traded event case for complete cross-spread limit order taking

---

src/rust/dbv2/migrations/2023-11-11-000000_optimizations/down.sql

There were some missing statements in `optimizations/down.sql` for triggers that were dropped in `optimizations/up.sql`.
This PR adds them back so that `diesel migration redo --all` works fine.

[ECO-952] fix reverse migrations

---

src/docker/aggregator/Dockerfile
src/docker/compose.dss-core.yaml
src/docker/compose.dss-global.yaml
src/docker/compose.dss-local.yaml

Update the docker dependencies so that the aggregator and processor do not start before diesel finishes executing.

[ECO-953] wait for diesel to finish before starting aggregator and processor

---

doc/doc-site/docs/overview/incentives.md

The multisig governance action at https://explorer.aptoslabs.com/txn/346773297?network=mainnet updated the incentive parameters for the Econia mainnet deployment
Update the incentive parameters docs accordingly

[ECO-991] Update incentives docs per vote

---

src/rust/aggregator/src/pipelines/user_history.rs

An edge case could happen where a transaction would fail with a message that says that the transaction might succeed if it is tried again. This PR changes the code so that error is gracefully ignored, and the aggregator doesn't stop.

[ECO-954] do not error out if transaction fails with specific message

---

src/rust/dbv2/migrations/2023-12-01-180017_healthcheck/down.sql
src/rust/dbv2/migrations/2023-12-01-180017_healthcheck/up.sql

This PR adds the `/rpc/healthcheck` endpoint which helps check that the data in the database is coherent.
To do this, `aggregator.user_history_last_indexed_txn` had to be exposed, and for consistency, `aggregator.candlesticks_last_indexed_txn` was exposed as well. They can respectively be queried at /user_history_last_indexed_txn` and `/candlesticks_last_indexed_txn`.
```http
GET /rpc/data_is_consistent
```
```json
true
```
```http
GET /data_status
```
```json
[
{
"current_time": "2023-12-15T19:29:33.023216+00:00",
"processor_last_txn_version_processed": 355183999,
"aggregator_user_history_last_txn_version_processed": 355183938,
"aggregator_candlesticks_last_txn_version_processed": [
[
60,
355183192
],
[
900,
355183192
],
[
1800,
355183192
],
[
14400,
355183192
],
[
86400,
355183192
],
[ …
```

[ECO-1005] Add healthcheck endpoint

---

src/docker/aggregator/Dockerfile
src/docker/compose.dss-global.yaml
src/docker/compose.processor-template.yaml
src/docker/processor/Dockerfile
src/docker/processor/start.sh

Make the processor restartable by getting the latest indexed txn from the db on startup.
Also copy instead of mount the config file.

[ECO-1055] make processor easly restartable

---

src/rust/dbv2/migrations/2023-12-20-202439_automatic_schema_reloading/down.sql
src/rust/dbv2/migrations/2023-12-20-202439_automatic_schema_reloading/up.sql

This PRs adds two Postgres triggers that will make sure the PostgREST schema is reloaded every time the database layout is updated.

[ECO-1084] add automatic schema reloading

---

src/rust/aggregator/sqlx_queries/rolling_volume/insert_daily_rolling_volume.sql

Somehow, this happened.
`NOT NULL` instead of `NULL`...
This PR fixes the bug and allows the correct aggregation of rolling volume.
The logic is the following:
If there is something in that table, we want to add the `dd > …` condition. If not, we want `dd` to be unrestricted.

hotfix the insert_daily_rolling_volume query

---

src/rust/aggregator/src/pipelines/order_history.rs

Somehow, one query was executing outside the transaction. Fixed that.

hotfix the order history pipeline

---

src/rust/aggregator/src/main.rs
src/rust/aggregator/src/pipelines/candlesticks.rs
src/rust/aggregator/src/pipelines/leaderboards.rs
src/rust/aggregator/src/pipelines/order_history.rs
src/rust/aggregator/src/pipelines/rolling_volume.rs
src/rust/aggregator/src/pipelines/user_history.rs
src/rust/aggregator/src/util.rs
src/rust/dbv2/check_db.sh
src/rust/dbv2/migrations/2024-01-07-231321_tvl/down.sql
src/rust/dbv2/migrations/2024-01-07-231321_tvl/up.sql

This PR adds the ~`/tvl`~ `/tvl_per_market` and `/tvl_per_asset` endpoints required to integrate with DeFi discovery tools.
Also added a dev script to check migrations really quickly without having to modify your main database (or even have one up !).
```http
GET /tvl_per_market
```
```json
[
{
"base_value": 1000000,
"quote_value": 10000000,
"market_id": 1,
"base_account_address": "0x5e156f1207d0ebfa19a9eeff00d62a282278fb8719f4fab3a586a0a2c0fffbea",
"base_module_name": "coin",
"base_struct_name": "T",
"base_name_generic": null,
"quote_account_address": "0x1",
"quote_module_name": "aptos_coin",
"quote_struct_name": "AptosCoin",
"base_name": "USD Coin",
"base_symbol": "USDC",
"base_decimals": 6,
"quote_name": "Aptos Coin",
"quote_symbol": "APT",
"quote_decimals": 8
}
]
```
```http
GET …
```

[ECO-1052] add tvl

---

src/rust/dbv2/migrations/2024-01-17-184459_coingecko/down.sql
src/rust/dbv2/migrations/2024-01-17-184459_coingecko/up.sql

This PR adds views and functions to create endpoints needed to integrate with CoinGecko.
See [provided doc](https://docs.google.com/document/d/1v27QFoQq1SKT3Priq3aqPgB70Xd_PnDzbOCiuoCyixw/edit).
This can take the usual PostgREST parameters, but since CoinGecko does not ask for any parameters to be implemented for this endpoint, they are not documented here.
[Here](https://postgrest.org/en/stable/references/api/tables_views.html) is a link for a more in depth description of PostgREST parameters.
[Here](https://econia.dev/off-chain/dss/rest-api#tag/place_swap_order_events) is a link to our internal API documentation.
```http
GET /tickers
```
```json
[
{
"market_id": 7,
"base_currency": "0x1::aptos_coin::AptosCoin",
"quote_currency": …
```

[ECO-1125] add views for integration with coingecko

---

src/rust/dbv2/migrations/2024-01-31-084306_volume_history/down.sql
src/rust/dbv2/migrations/2024-01-31-084306_volume_history/up.sql

This PR adds the `/rpc/volume_history` endpoint which returns the total and daily volume at a given timestamp.
This is done in order to support the DefiLlama integration.
```http
GET /rpc/volume_history?market_id=7&time=2023-12-01
```
```json
[
{
"daily": 13850323219,
"total": 92596968702
}
]
```

[ECO-1182] add volume history endpoint

---

src/rust/sdk/README.md
src/rust/sdk/src/entry.rs
src/rust/sdk/src/errors.rs
src/rust/sdk/src/lib.rs
src/rust/sdk/src/view.rs

Add some more Rust doc before publishing the crate to make reading the doc and using the crate more intuitive.

[ECO-1153] add more documentation before publishing the rust crate

---

src/rust/aggregator/src/main.rs

This PR adds rolling volume as a default pipeline as it is now a core dependency for the `/volume_history` endpoint.

[ECO-1192] add rolling volume as a default pipeline

---

src/terraform/dss-ci-cd/dss/modules/aggregator/main.tf

The rolling volume endpoint will be required on community DSS deployments to support DeFi LLama integration. Remove the config in anticipation for it to become a default pipeline per https://github.com/econia-labs/econia/pull/683

[ECO-1194] Remove aggregator rolling volume extra config

---

src/rust/Cargo.lock
src/rust/sdk/Cargo.toml
src/rust/types/Cargo.toml

Some of the links in `Cargo.toml`s were outdated/missing.
This PR updates that.

[ECO-1199] update rust packages metadata

---

doc/doc-site/docs/off-chain/dss/changelog.md

Add a period to a bullet point that is missing one, to enforce stylistic consistency.

[ECO-1275] Correct inconsistent formatting in DSS changelog

---

src/rust/.sqlx/query-6d0ae6fd5f1dca3a60979fcf01611c95a5d2ea96678841c51fd04de89bf757de.json
src/rust/.sqlx/query-7abb8665afc6387f18c86596d78732295810b8d134ce633e590a09098c1b277c.json
src/rust/.sqlx/query-c4604c7e125351bac2954a191260af83205710d32561bbab5dafec0d872d2b54.json
src/rust/.sqlx/query-c9496ff3014e7c623e886775b92509d612190a3a4d101c05ddc84e1428a7faec.json
src/rust/.sqlx/query-cc462e52c6ec09a136bf9357d4434ff325cd3a56926fa1e7829e552ab8eeac9c.json
src/rust/.sqlx/query-e30bb0204bdfd3aac19f247eff3245cadb89d8ff7b8d677a2aad9d37f60b7b8d.json
src/rust/aggregator/sqlx_queries/spreads/get_cancel_order_events_between_txn_versions.sql
src/rust/aggregator/sqlx_queries/spreads/get_change_order_size_events_between_txn_versions.sql
src/rust/aggregator/sqlx_queries/spreads/get_fill_events_between_txn_versions.sql
src/rust/aggregator/sqlx_queries/spreads/get_last_indexed_timestamp.sql
src/rust/aggregator/sqlx_queries/spreads/get_latest_event_timestamp.sql
src/rust/aggregator/sqlx_queries/spreads/get_max_txn_version_before_timestamp.sql
src/rust/aggregator/sqlx_queries/spreads/get_place_limit_order_events_between_txn_versions.sql
src/rust/aggregator/sqlx_queries/spreads/init_last_indexed_timestamp.sql
src/rust/aggregator/sqlx_queries/spreads/insert_spread.sql
src/rust/aggregator/sqlx_queries/spreads/update_last_indexed_timestamp.sql
src/rust/aggregator/src/main.rs
src/rust/aggregator/src/pipelines.rs
src/rust/aggregator/src/pipelines/spreads.rs
src/rust/dbv2/migrations/2024-02-12-145642_spreads/down.sql
src/rust/dbv2/migrations/2024-02-12-145642_spreads/up.sql

This PR adds a new table that can be used to get min ask, max bid, spread and mid price.
```http
GET /spreads
```
```json
[
{
"market_id": 7,
"time": "2023-12-26T08:11:00+00:00",
"min_ask": 10990,
"max_bid": 9510
}
]
```

[ECO-1280] add spreads

---

src/docker/compose.dss-core.yaml
src/docker/compose.dss-global.yaml
src/docker/compose.processor-template.yaml
src/docker/example.env

To resolve a few issues that arose while operating the node, added several options to the docker-compose file.
1. Add option `restart: unless-stopped` to 
1. aggregator
2. postgrest
3.  ws
4. processor
2. Add enviroment value `PGRST_DB_MAX_ROWS:500` to postgrest

Add restart option and postgrest max row environment

---

src/docker/example.env

Change the word `malious` to `malicious`, introduced in #699

[ECO-1301] Fix typo in config file

---

src/terraform/dss-ci-cd/scripts/upload-base64-text-to-file.sh

This PR fixes an issue with the script where the output of the `base64` command would be treated as multiple lines, and thus commands, by `bash`.

[ECO-1322] fix quoting issue in terraform script

---

src/terraform/dss-ci-cd/scripts/hot-upgrade.sh

Escape quotes in hot upgrade script for cross-platform usability

[ECO-1325] Escape quotes in hot upgrade script

---

src/terraform/dss-ci-cd/dss/modules/aggregator/main.tf

Since the order history pipeline was removed, this needs to be removed from terraform as well.

[ECO-1344] remove order-history from terraform aggregator args

---

src/rust/dbv2/migrations/2024-03-11-101756_grafana_allow_tvl/down.sql
src/rust/dbv2/migrations/2024-03-11-101756_grafana_allow_tvl/up.sql

In order to display graphs like vol/TVL, we need access to the TVL tables in Grafana.

[ECO-1349] allow grafana to access tvl tables

---

doc/doc-site/docs/off-chain/dss/gcp.md

Remove a dead link to WS docs from an old deployment guide

[ECO-1359] Remove dead link to WebSockets Docs

---

src/rust/Cargo.lock
src/rust/mqtt-publisher/Cargo.toml
src/rust/mqtt-publisher/src/main.rs

Order IDs (and all big numerical values) were getting truncated due to the implementation of deserialize and serialize of the [bigdecimal](https://github.com/akubera/bigdecimal-rs) Rust crate (see akubera/bigdecimal-rs#117). We now just use u128s to avoid that, since none of the values are bigger than [u128::MAX](https://doc.rust-lang.org/std/primitive.u128.html#associatedconstant.MAX) anyways.

[ECO-1423] fix order id rounding

---

doc/doc-site/docs/off-chain/dss/mqtt.md

This PR fixes a broken link in the docs that prevented the docs from compiling.

[ECO-1429] fix broken link in docs

---

src/docker/compose.dss-core.yaml
src/docker/mqtt/mosquitto.conf
src/terraform/dss-ci-cd/dss/modules/db/main.tf

This is needed so that browsers can subscribe to MQTT topics.

[ECO-1444] add MQTT over WS support

---

src/rust/.sqlx/query-16a97d275816539edd170312e678908210c38d52775966fb33ba2fe035713b96.json
src/rust/aggregator/sqlx_queries/order_history_pipelines/insert_new_liquidity_groups.sql
src/rust/aggregator/src/pipelines/order_history_pipelines.rs

This PR makes it so that an 'æll' liquidity group is created by default.

[ECO-1432] add all group by default

---

doc/doc-site/docs/off-chain/dss/changelog.md
doc/doc-site/docs/off-chain/dss/data-service-stack.md

1. Add a hot upgrade section to the DSS landing page
2. Annotate v2.0.1 as hot upgradable
3. Update release procedure with hot upgrade step

[ECO-1452] Add hot upgrade docs support

---

src/rust/dbv2/migrations/2024-03-22-105856_handle_leading_zeros/down.sql
src/rust/dbv2/migrations/2024-03-22-105856_handle_leading_zeros/up.sql

1. Add a migration to strip leading zeroes from event handles
2. Bump the submodule per https://github.com/econia-labs/aptos-indexer-processors/pull/25

[ECO-1451] strip leading zeros in handles

---

doc/doc-site/docs/off-chain/dss/ci-cd.md
src/terraform/dss-ci-cd/scripts/resume-runner.sh
src/terraform/dss-ci-cd/scripts/suspend-runner.sh

This PR adds two scripts to suspend and resume the runner on GCP to reduce running costs.

[ECO-1276] add suspend/resume runner scripts

---

doc/doc-site/docs/off-chain/python-sdk.md
doc/doc-site/docs/off-chain/rust-sdk.md
src/python/sdk/econia_sdk/lib.py
src/rust/Cargo.lock
src/rust/Cargo.toml
src/rust/e2e/src/utils.rs
src/rust/sdk/Cargo.toml
src/rust/sdk/example/src/main.rs
src/rust/sdk/src/errors.rs
src/rust/sdk/src/lib.rs

This PR adds support to add an API key when using the Rust or Python SDK.

[ECO-1478] update sdk to accept api key

---

src/python/sdk/pyproject.toml
src/rust/sdk/Cargo.toml

This PR bumps the version number of both the Rust SDK and the Python SDK as they were recently updated.

[ECO-1500] bump sdk versions

---

src/rust/dbv2/migrations/2024-04-10-175509_fix_tickers/down.sql
src/rust/dbv2/migrations/2024-04-10-175509_fix_tickers/up.sql

There was a problem as `web_anon` did not have the right to query the `aggregator` schema.
That was fixed by replacing refs to the `aggregator` schema by  the `api` schema.
The rights on the `api` schema were also given to `web_anon` where needed.

[ECO-1520] fix tickers

---

doc/doc-site/docs/integrators/reference-frontend.md

Adding the `NEXT_PUBLIC_INTEGRATOR_ADDRESS` to the local section, just to be more explicit

[ECO-1523] Add integrator address env variable to the local section

---

doc/doc-site/docs/off-chain/dss/changelog.md

Bump release candidate to full release per recent downed processors on outdated upstream code

[ECO-1559] Bump v2.1.0 rc to full release

---

src/rust/.cargo/config.toml
src/rust/Cargo.lock
src/rust/Cargo.toml
src/rust/aggv2/Cargo.toml
src/rust/aggv2/README.md
src/rust/aggv2/src/feed.rs
src/rust/aggv2/src/feed/liquidity.rs
src/rust/aggv2/src/feed/spread.rs
src/rust/aggv2/src/feed/state.rs
src/rust/aggv2/src/feed/volume.rs
src/rust/aggv2/src/main.rs
src/rust/aggv2/src/numeric.rs
src/rust/dbv2/migrations/2024-04-01-112425_add_pkey_to_rolling_volume_history/down.sql
src/rust/dbv2/migrations/2024-04-01-112425_add_pkey_to_rolling_volume_history/up.sql
src/rust/dbv2/migrations/2024-04-09-142800_aggv2/down.sql
src/rust/dbv2/migrations/2024-04-09-142800_aggv2/up.sql

This PR adds an experimental aggregator build that should improve performance over the old one.
To test this PR, spin up the DSS with just the DB and the processor (`docker compose -f compose.dss-core.yaml up -d postgres diesel processor`).
Once up, you can start the new aggregator by going to `src/rust` and running `cargo run -p aggv2`.

[ECO-1477] add experimental aggregator build

---

doc/doc-site/docs/off-chain/dss/changelog.md
src/rust/dbv2/migrations/2024-05-01-120043_fix_nominal/down.sql
src/rust/dbv2/migrations/2024-05-01-120043_fix_nominal/up.sql

This PR fixes the `base_volume_nominal` field in the `/tickers` endpoint.
- Connect to the SQL instance of `hot-208`
- Type `begin;`
- Paste the `up.sql` file and run
- `SELECT * FROM api.tickers` and triple check the data
- Spin up DSS
- Sync
- `SELECT * FROM api.tickers` and triple check the data

[ECO-1624] fix nominal error in /tickers endpoint

---

doc/doc-site/docs/off-chain/dss/changelog.md
src/rust/dbv2/migrations/2024-04-26-152225_optimize_markets/down.sql
src/rust/dbv2/migrations/2024-04-26-152225_optimize_markets/up.sql

This PR vastly improves the performance of the `api.markets` SQL view. This
will help DSS providers lower their infrastructure costs, since this is a very
used endpoint, and will lower their CPU/disk usage.
Note that price 24h ago is now using the new `prices` table, which means it is
a weighted price over a 1 min period instead of an instant and quite random
fill price.
- Spin up a DSS instance.
- Sync.
- `curl localhost:3000/markets` and compare with `curl https://aptos-mainnet-econia.nodeinfra.com/markets`
- Results should be the same within margin of error.

[ECO-1597] improve preformance of api.markets

---

doc/doc-site/docs/off-chain/dss/changelog.md
src/rust/Cargo.lock
src/rust/Cargo.toml
src/rust/aggregator/Cargo.toml
src/rust/aggv2/Cargo.toml
src/rust/dbv2/Cargo.toml

This PR updates the Rust deps (`bigdecimal`, `sqlx` and `diesel`) to be compatible with the Aptos processor repo.
- Clone.
- Run `cargo check` inside `src/rust`.
- Run `cargo check` inside `src/rust/dependencies/aptos-indexer-processors/rust/processor`.

[ECO-1643] fix and update deps

---

doc/doc-site/docs/off-chain/dss/changelog.md
src/rust/dbv2/migrations/2024-05-10-100712_fix_price_nominal/down.sql
src/rust/dbv2/migrations/2024-05-10-100712_fix_price_nominal/up.sql

This PR fixes a function that wrongly calculates nominal price when tick size is not 1.
Spin up DSS, query `/tickers`.

[ECO-1656] fix price when tick size isn't 1

---

doc/doc-site/docs/off-chain/dss/ci-cd.md
doc/doc-site/docs/off-chain/dss/data-service-stack.md
src/docker/example.env

This PR updates the documentation and replaces the link from the old Aptos API
key generator to the new one.

[ECO-1704] update aptos website to get api keys

---

doc/doc-site/docs/off-chain/dss/changelog.md
src/rust/dbv2/migrations/2024-05-22-111841_fix_market_24h_price/down.sql
src/rust/dbv2/migrations/2024-05-22-111841_fix_market_24h_price/up.sql

This PR fixes the 24h price and everything related to this field in the
`/markets` endpoint.
Currently, when there has been no price in the last 24 hours, the last price
will be used, no matter when it happened.
This is not expected behaviour.
If there was no activity in the last 24 hours, `last_fill_price_24hr`,
`price_change_as_percent_24hr`, `price_change_24hr` should be null. This PR
fixes that.

[ECO-1684] fix 24h price when missing

---

doc/doc-site/docs/off-chain/dss/changelog.md
src/rust/dbv2/migrations/2024-06-17-090914_fix_rpc_volume_history/down.sql
src/rust/dbv2/migrations/2024-06-17-090914_fix_rpc_volume_history/up.sql

This PR fixes the `volume_history` endpoint.
Since the rolling volume pipeline was changed to not create an event when no activity is present on a market, that broke the `volume_history` endpoint.
It was now updated to use candlestick data rather than rolling volume.

[ECO-1853] use candlesticks for instant volume

---

.github/workflows/verify-doc-site-build.yaml
doc/doc-site/pnpm-lock.yaml

1. Add a GitHub actions check that verifies the docs site builds.
1. Update `pnpm` lockfile to match version pinned in action spec.
1. CI passes

[ECO-1879] Add doc site build check

---

.github/workflows/verify-doc-site-build.yaml
doc/doc-site/docs/off-chain/dss/changelog.md

Update submodule to use v1.15.1 of the aptos indexer.
Spin up DSS.

[ECO-1909] update processor submodule (v1.15.1)

---

doc/doc-site/docs/off-chain/dss/changelog.md

Fix indexer submodule.
It was updated to the wrong version last time.

[ECO-1963] fix submodule

---

doc/doc-site/docs/off-chain/dss/changelog.md
src/rust/aggregator/src/pipelines/coins.rs

Currently, the coins pipeline does not work for addresses that start with 0x0. This PR fixes that.
Run DSS.

[ECO-1971] fix coins pipeline for coins starting with 0x0

---

doc/doc-site/docs/off-chain/dss/changelog.md
src/rust/Cargo.lock

The DSS wasn't building inside of docker compose.
This is due to the compilation of the aggregator, which depends on the `time` crate, which could not compile.
Updating the crate solved the issue.
Delete this line and provide a description of how to test the changes in this
PR.

[ECO-2045] Fix docker compose build by updating the time crate

---

src/rust/e2e/src/market_registration.rs
src/rust/sdk/example/src/main.rs
src/rust/sdk/src/lib.rs

I want to use `Arc` share/clone Rust SDK EconiaClient, but submit_tx of EconiaClient is mutable can't used inside `Arc` by ref.
I notice that submit_tx mut sequence_number of account, but it is a **Atomic do not require mut ref** to modified it, So submit_tx do not need mutable and safely used inside Arc
cargo build
> If a task does not apply to your PR, strike it through and mark it complete:
This change is compatible with previous usage of submit_tx no need to write changelog
```md
```

Remove mut in Rust sdk submit_tx

---

src/rust/dbv2/migrations/2024-09-11-150020_optimize_querying_orders_by_order_id/down.sql
src/rust/dbv2/migrations/2024-09-11-150020_optimize_querying_orders_by_order_id/up.sql

This PR adds an index to speed up querying orders by order id.

[ECO-2123] Add index to speed up querying orders by order_id

---

src/rust/dbv2/migrations/2024-09-20-111458_add_query_time_limit/down.sql
src/rust/dbv2/migrations/2024-09-20-111458_add_query_time_limit/up.sql

This PR adds a maximum time to queries made by PostgREST.
This will prevent users hogging all DB connections.
Noting that all other roles can still make long queries, which means other tools like grafana can still use the DB like before.

[ECO-2194] Add limit to query time

---

doc/doc-site/docs/off-chain/dss/changelog.md

This PR updates the changelog for the DSS v2.5.0 rc 2 release

[ECO-2199] Update changelog

---

src/move/econia-wrapper-demo/Move.toml
src/move/econia-wrapper-demo/README.md
src/move/econia-wrapper-demo/sources/cancel_and_place.move

The wrapper for batch replace sometimes errors out when an order gets filled
just before the cancel instruction comes in.
1. Add a check to verify the market has an open order with the given order ID
before trying to cancel it.
1. Bump version in `Move.toml`.
1. Add `dev-addresses` for easier checking with `aptos move compile --dev`.
See successful testnet transactions added to README.

[ECO-2324] Add open order check to batch replace wrapper
