econia-labs/econia

src/move/econia/Move.toml, src/move/econia/sources/coins.move
@alnoki This seems to be enough to make it compile!
=> devnet update

doc/doc-site/src/css/custom.css
1. Needs testing on larger screen. Unfortunately don't have a larger screen on hand right now to test.
2. Updated
3. Updated
4. Also needs testing on larger screen
5. Punting for now as I haven't found a good way to change the styles on that component
=> Address comments for doc style

doc/doc-site/src/css/custom.css
=> Fix pagination item line-height and padding

doc/doc-site/src/css/custom.css
This PR serves as a preview. Needs design input before merging as we are not 100% sure this is the style we want yet.
=> Use primary/secondary style for prev/next buttons

scripts.sh
This reverts commit 5e5e5862eb23ea5e4b43e22b1d30c884642a4750.
=> Revert "Add toolchain support per #108, closes #108"

.github/workflows/deploy-api.yml, src/rust/api/sqlx-data.json
Run docker build with src/rust as working directory
=> ECO-117: Fix working directory for GitHub Actions

src/move/econia/doc/market.md, src/move/econia/sources/market.move
=> Rename `max_lots` temporary variable (#185)

src/typescript/frontend/src/pages/trade/[market_name].tsx
=> Restyle each chart card to match Figma

src/typescript/frontend/src/components/trade/OrdersTable.tsx, src/typescript/frontend/src/hooks/useUserOrders.tsx, src/typescript/frontend/src/pages/trade/[market_name].tsx, src/typescript/frontend/src/types/api.ts
=> Add Orders Table

src/typescript/frontend/src/components/trade/OrdersTable.tsx, src/typescript/frontend/src/components/trade/TradeHistoryTable.tsx, src/typescript/frontend/src/hooks/useUserOrderHistory.tsx, src/typescript/frontend/src/hooks/useUserOrders.tsx, src/typescript/frontend/src/pages/trade/[market_name].tsx, src/typescript/frontend/src/types/api.ts, src/typescript/frontend/src/utils/market.ts
=> Add TradeHistoryTable

src/rust/api/src/main.rs, src/rust/types/src/query.rs
Avoid printing ANSI characters to GCP cloud logging
=> Tracing settings for prod environment

src/typescript/frontend/src/pages/_app.tsx
=> Enable toasts + toast style

src/typescript/frontend/src/components/trade/OrderEntry/LimitOrderEntry.tsx, src/typescript/frontend/src/contexts/AptosContext.tsx, src/typescript/frontend/src/pages/_app.tsx, src/typescript/frontend/src/pages/faucet/index.tsx
=> Refactor signAndSubmitTransaction

src/typescript/frontend/src/hooks/useOrderbook.ts
hook needed for both orderbook and depth chart components.
=> add useorderbook hook

src/typescript/frontend/src/components/trade/DepositWithdrawModal/DepositWithdrawContent.tsx, src/typescript/frontend/src/components/trade/DepositWithdrawModal/InitialContent.tsx, src/typescript/frontend/src/components/trade/OrderEntry/LimitOrderEntry.tsx, src/typescript/frontend/src/components/trade/OrderEntry/MarketOrderEntry.tsx, src/typescript/frontend/src/components/trade/TVChartContainer.tsx, src/typescript/frontend/src/contexts/AptosContext.tsx, src/typescript/frontend/src/hooks/useCoinBalance.ts, src/typescript/frontend/src/hooks/useCoinInfo.ts, src/typescript/frontend/src/hooks/useOrderbook.ts, src/typescript/frontend/src/pages/faucet/index.tsx, src/typescript/frontend/src/types/econia.ts, src/typescript/frontend/src/types/move.ts, src/typescript/frontend/src/utils/TypeTag.ts, src/typescript/frontend/src/utils/econia.ts
Also refactor types into respective files and move TypeTag into utils/
=> Show market account balance in deposit/withdraw modal

src/typescript/frontend/pnpm-lock.yaml, src/typescript/frontend/src/components/trade/DepositWithdrawModal/DepositWithdrawContent.tsx, src/typescript/frontend/src/components/trade/DepositWithdrawModal/index.tsx, src/typescript/frontend/src/components/trade/OrderEntry/LimitOrderEntry.tsx, src/typescript/frontend/src/hooks/useMarketAccountBalance.ts, src/typescript/frontend/src/mockdata/README.md, src/typescript/frontend/src/mockdata/markets.ts, src/typescript/frontend/src/pages/trade/[market_name].tsx, src/typescript/frontend/src/pages/trade/index.tsx
Also, move some mock data to `mockdata/` for consolidation
=> Display market account balances in LimitOrderEntry

src/rust/api/sqlx-data.json, src/rust/db/examples/seed_db.rs
Needed because Wi-FI at the hackathon is slow
=> Seed db batch insert

src/typescript/frontend/src/components/trade/OrderEntry/OrderEntryInputWrapper.tsx
found the culprit...
it's the length of the adornments.
solution feels hacky, open to better suggestions
=> ECO-171: consistent limit order sizing

README.md
=> Revert test change

README.md
=> Add test change

src/typescript/frontend/src/components/OrderbookTable.tsx, src/typescript/frontend/src/components/StatsBar.tsx, src/typescript/frontend/src/components/trade/OrderEntry/MarketOrderEntry.tsx
=> ECO-253 ECO-249 ECO-238

src/move/econia/doc/market.md, src/move/econia/sources/market.move
Posts below min size enabled through #347 
https://github.com/econia-labs/econia/pull/347#discussion_r1268866405
=> [ECO-259] Update comment for post below min size

src/move/econia/Move.toml, src/python/sdk/econia_sdk/entry/market.py, src/python/sdk/econia_sdk/lib.py, src/python/sdk/econia_sdk/types.py, src/python/sdk/econia_sdk/view/incentives.py, src/python/sdk/econia_sdk/view/market.py, src/python/sdk/econia_sdk/view/registry.py, src/python/sdk/econia_sdk/view/resource_account.py, src/python/sdk/econia_sdk/view/user.py, src/python/sdk/examples/trade.py, src/python/sdk/pyproject.toml
General summary:
This PR adds a bunch of view function accessors, as far as I know comprehensively, to the Python SDK. It also adds event accessors although not comprehensively. This new code is then used by an example script which goes through the motions of various trading situations and describes the results. It is possible to interrupt this script and re-run it while still getting correct situations simulated and correct outcomes described.
Example run (dry run w/o environment variables set would have two more prompts at the beginning):
```
Please enter the URL of an Aptos node (enter nothing to default to devnet OR re-run with APTOS_NODE_URL environment variable)
Please enter the URL of an Aptos faucet (enter nothing to default to devnet OR re-run with APTOS_FAUCET_URL environment …
```
=> [ECO-240] Create Python example script for new market events

doc/doc-site/docs/off-chain/python-sdk.md, src/python/sdk/econia_sdk/view/user.py, src/python/sdk/examples/trade.py
I've made an overview of the Python SDK here. We need to make a tutorial for the example script along with an explanation of its output. The reader is assumed to be debugging disinclined so the instructions must be workable in all cases. I then
=> [ECO-185] Create example script walkthrough

src/typescript/frontend/src/components/OrderbookTable.tsx
=> Use CSS linear gradient for orderbook bars

src/typescript/frontend/src/components/trade/TVChartContainer.tsx
also reversed order to match tradingview.com
also may want to check the `resolution`
=> ECO-252 Trading View All-Time

doc/doc-site/README.md, doc/doc-site/docs/glossary.md, doc/doc-site/sidebar.js
This PR adds a glossary based on the Aptos glossary: https://aptos.dev/reference/glossary/
A select few terms are included to demonstrate formatting standards
=> [ECO-225] Add glossary, preliminary term set

src/python/sdk/pyproject.toml
We need to upload the decimal guidance changes to PyPi and this requires a version bump
=> Upgrade python sdk version

src/typescript/frontend/src/components/trade/TradeHistoryTable.tsx
quick one
https://linear.app/econia-labs/issue/ECO-349/fix-loading-error
=> ECO-349 fixed table cell width

src/rust/db/src/models/market.rs, src/rust/sdk/src/entry.rs, src/rust/sdk/src/errors.rs, src/rust/sdk/src/lib.rs, src/rust/sdk/src/view.rs, src/rust/types/src/events.rs, src/rust/types/src/order.rs
Core changes:
- Add missing entry functions:
- `init_market_event_handles_if_missing`.
- `place_market_order_user_entry`.
- Add `view.rs` file which contains:
- a struct named `EconiaViewClient` which can query every view function of the contract. Some functions which results can be calculated without blockchain data are calculated locally. Functions which are calculated locally instead of reaching out to the blockchain are identifiable through a note in the function's documentation comment.
- structs which represent some view functions return type.
- Add missing event types:
- `MakerEvent`.
- `TakerEvent`.
- Update old events which did not deserialize correctly (`base_*` and `quote_*` replaced with `base_type` and `quote_type`).
- Re-export `econia_types` as `types`.
- Add …
=> [ECO-228] Update Rust SDK

src/typescript/frontend/src/components/trade/OrdersTable.tsx, src/typescript/frontend/src/pages/trade/[market_name].tsx
couldn't find the missing border that the issue was talking about
https://linear.app/econia-labs/issue/ECO-331/fix-background-bug
=> ECO-331 Fix background bug -- grain not showing up

src/rust/aggregator/README.md
This README currently contains the architecture of the aggregator.
=> [ECO-405] Add readme to aggregator

.vscode/settings.json, doc/doc-site/docs/integrators/audits.md, doc/doc-site/docs/integrators/econia-labs.md, doc/doc-site/docs/move/changelog.md, doc/doc-site/docs/off-chain/events.md, doc/doc-site/docs/security.md, doc/doc-site/docs/welcome.md, doc/doc-site/sidebar.js
This PR updates the docs site for the recent audit of Econia v4.1.0, and adds a few tweaks that were encountered along the way.
=> [ECO-433] Update docs for audit, assorted fixes

src/rust/db/src/models/order.rs, src/rust/types/src/events.rs
There are (were) some errors in this code. All of them had quick fixes which do seem to have resolved the errors. Need to clear these out so the only errors I see are mine and I can be alerted to problems.
=> [ECO-467] Fix outstanding errors in rust code

doc/doc-site/docs/off-chain/python-sdk.md, src/python/sdk/examples/trade.py, src/rust/sdk/example/src/main.rs
This PR adds unified leading 0x guidance to Python/Rust trading scripts and docs
=> [ECO-455] Create unified leading 0x guidance

src/move/testnet-competition-throttler/sources/throttle.move
This PR fixes max volume arithmetic on the testnet trading competition throttler
=> [ECO-491] Tweak max volume arithmetic

src/move/testnet-competition-throttler/sources/throttle.move
This PR updates the transfer and trade amounts for the throttler
=> [ECO-492] Recalibrate throttler values

src/typescript/frontend/src/components/Header.tsx
=> ECO-478: add flex to container to "shrink" link tag to image size

src/docker/compose.dss-local.yaml, src/rust/dbv2/migrations/2023-08-25-111710_add_market_registration_events/up.sql, src/rust/dbv2/migrations/2023-09-04-113144_postgrest/down.sql, src/rust/dbv2/migrations/2023-09-04-113144_postgrest/up.sql, src/rust/dbv2/migrations/2023-09-20-065710_event_types/up.sql, src/rust/dbv2/migrations/2023-09-20-193413_add_limit_order_events/up.sql
- use a 32 char long secret
- update message format to correspont to what postgres-websockets is expecting
- add missing drop in down migration (postgrest migration)
=> fix websockets

src/move/testnet-competition-throttler/Move.toml, src/move/testnet-competition-throttler/README.md, src/move/testnet-competition-throttler/sources/throttle.move
This PR merges the throttler from `testnet` into the `main` branch for posterity
=> [ECO-559] Merge throttler into main branch

doc/doc-site/docs/off-chain/websocket.md
Add documentation explaining what data the WebSocket service returns.
=> [ECO-569] Add ws documentation

doc/doc-site/docs/move/changelog.md
=> [ECO-568] Fix changelog typo

doc/doc-site/docs/off-chain/dss/data-service-stack.md, doc/doc-site/docs/off-chain/dss/websocket.md
Fix broken internal docs site links introduced in #506
=> [ECO-571] Resolve broken links in docs site

src/typescript/frontend/src/components/StatsBar.tsx, src/typescript/frontend/src/components/modals/flows/DepositWithdrawFlowModal.tsx, src/typescript/frontend/src/components/modals/flows/WalletButtonFlowModal.tsx, src/typescript/frontend/src/components/trade/DepositWithdrawModal/index.tsx
wrong branch name, issue linked: https://linear.app/econia-labs/issue/ECO-448/market-select-modal-styling
Fix market select styling
=> Eco 448: market select padding

src/typescript/frontend/src/components/MarketIconPair.tsx, src/typescript/frontend/src/components/trade/DepositWithdrawModal/SelectMarketContent.tsx
=> ECO-348: sticky header market select

src/typescript/frontend/src/components/modals/BaseModal.tsx
modals with close button on hover will turn blue:
=> close button border blue

doc/doc-site/docs/off-chain/dss/websocket.md
This PR adds `recognized_market_event` to `websocket.md` now that we have these events.
---
Verified using...
Processor config:
```
health_check_port: 8085
server_config:
processor_config:
type: econia_transaction_processor
econia_address: 0xeeee0dd966cd4fc739f76006591239b32527edbb7c303c431f8c691bda150b40
postgres_connection_string: postgres://econia:econia@postgres:5432/econia
indexer_grpc_data_service_address: http://streamer:50051
indexer_grpc_http2_ping_interval_in_secs: 60
indexer_grpc_http2_ping_timeout_in_secs: 10
auth_token: dummy_token
starting_version: 0
```
Trade script:
```
(base) egd@Elliotts-MacBook-Pro sdk % poetry run trade                                   
Enter the minimum order size to (re-)use for the market (enter nothing to default to 500==0.5 APT)
Enter the …
```
=> [ECO-634] Add recognized_market_event to docs

src/rust/dbv2/migrations/2023-10-06-164142_leaderboards/down.sql, src/rust/dbv2/migrations/2023-10-06-164142_leaderboards/up.sql, src/rust/dbv2/src/schema.rs
This PR adds migration suggestions from a review on #531 
Testing:
From Econia repo root:
```sh
docker compose --file src/docker/compose.database.yaml up
```
From Econia repo root, different terminal:
```sh
cd src/rust/dbv2
export DATABASE_URL=postgres://econia:econia@localhost:5432/econia
diesel database reset 
print-schema
```
=> [ECO-663] Add migration suggestions

src/move/testnet-competition-throttler/README.md, src/move/testnet-competition-throttler/sources/throttle.move
Update throttler wait time to 10 s
This requires making a new type
=> [ECO-669] Update throttler wait time to 10 s

src/move/testnet-competition-throttler/sources/throttle.move
Update function signatures to enable backward compatibility
=> [ECO-670] Enforce throttler backward compatibility

src/move/testnet-competition-throttler/README.md, src/move/testnet-competition-throttler/sources/throttle.move
The throttler has been updated to allow wait times in seconds
Merge it to main for posterity
=> [ECO-671] Merge throttler to main

doc/doc-site/docs/off-chain/dss/gcp.md
* Add section on granting project permissions
* Add diagnostics commands
* Remove `latest` specifiers, opting for image refresh per https://stackoverflow.com/a/56068456
* Delete processor and aggregator instances, refresh postgres since it has static IP addresses
* Consolidate redeployment commands to always specify processor config
=> [ECO-657] Update GCP walkthrough

src/rust/aggregator/src/data.rs, src/rust/aggregator/src/data/markets.rs, src/rust/aggregator/src/data/user_history.rs, src/rust/aggregator/src/main.rs
Remove duplicated text in logs and add timed logs.
=> [ECO-786] improve logging

src/move/econia/sources/avl_queue.move, src/move/econia/sources/market.move, src/move/econia/sources/user.move
Add pagination for price level view function due to VM execution errors (exhausting gas during execution)
Move unit tested to 100% coverage
=> [ECO-821] Add paginated price level view function

src/move/econia/sources/market.move, src/move/econia/sources/user.move
Add pagination for getting open orders
=> [ECO-823] Paginate open orders

src/terraform/leaderboard-backend/main.tf
Incorporate hot fix for processor insertion from https://github.com/econia-labs/aptos-indexer-processors/pull/16, IP rate limit tuning from #567
=> [ECO-822] Incoporate hot fix for processor insertion

doc/doc-site/docs/integrators/oracles/pyth.md
Update dead links to Pyth docs
=> [ECO-832] Fix dead Pyth links

src/rust/dbv2/migrations/2023-11-02-142200_deduped_fills/down.sql, src/rust/dbv2/migrations/2023-11-02-142200_deduped_fills/up.sql
* Add deduped fill events view migrations
* Verified via http://localhost:3000/fill_events_deduped?txn_version=gt.750000000&limit=5:
```json
[
{
"txn_version": 750000216,
"event_idx": 3,
"emit_address": "0x5bc80990c4105df90cb0f15fc145ee83edacf5446036413aca7f69e5c2ccd241",
"time": "2023-11-01T22:07:43.95604+00:00",
"maker_address": "0x5bc80990c4105df90cb0f15fc145ee83edacf5446036413aca7f69e5c2ccd241",
"maker_custodian_id": 0,
"maker_order_id": 46187935566736706177604623,
"maker_side": true,
"price": 7183,
"sequence_number_for_trade": 0,
"size": 100000,
"taker_address": "0x23d11784f549f195de5dfed18f29047541683335056d00ea601b20ba005901cd",
"taker_custodian_id": 0,
"taker_order_id": 67219049960882068030226432,
"taker_quote_fees_paid": 359150
},
{
"txn_version": 750000921, …
```
=> [ECO-846] Add deduped fill events view

doc/doc-site/docs/off-chain/dss/websocket.md
Remove unnecessary indefinite article
=> [ECO-854] Clean up docs typo

doc/doc-site/docs/move/changelog.md, src/move/econia/doc/avl_queue.md, src/move/econia/doc/market.md, src/move/econia/sources/avl_queue.move, src/move/econia/sources/market.move, src/move/econia/sources/user.move
@chen-robert
* Pagination order ID arguments
* Add order ID side checks
* Abstract order ID check function
* Update tests
* AVL queue next list node iterator function
* Add test in AVL queue module
* Update doc comments, rebuild docs as needed
* Update Move changelog with this PR
* Test to 100% coverage per b01f67b , ea0f02b
=> [ECO-867] Incorporate audit feedback

src/rust/dbv2/migrations/2023-11-06-213153_price_levels/down.sql, src/rust/dbv2/migrations/2023-11-06-213153_price_levels/up.sql
Add `/price_levels` endpoint.
---
```http
GET /price_levels?market_id=eq.3&limit=10
```
```json
[{"market_id":3,"side":"bid","price":1000,"version":123456789,"total_size":10000},
{"market_id":3,"side":"bid","price":1100,"version":123456789,"total_size":1000},
{"market_id":3,"side":"bid","price":1500,"version":123456789,"total_size":10900},
{"market_id":3,"side":"bid","price":2999,"version":123456789,"total_size":235877498},
{"market_id":3,"side":"bid","price":5000,"version":123456789,"total_size":2502000},
{"market_id":3,"side":"bid","price":5500,"version":123456789,"total_size":1000},
{"market_id":3,"side":"bid","price":5700,"version":123456789,"total_size":1000},
{"market_id":3,"side":"bid","price":5800,"version":123456789,"total_size":1000}, …
```
=> [ECO-837] add price levels

src/move/econia/Move.toml, src/move/faucet/Move.toml
Restore local dependencies broken by merge action
=> Fix Move.toml changes from #632

doc/doc-site/docs/integrators/bridges.md
Add tutorial section for bridges page on docsite.
=> Add USDC (LayerZero) tutorial

src/docker/compose.dss-core.yaml
#644 forced services to wait for diesel, but did not update postgrest
Update postgrest to wait for diesel to finish before running
=> [ECO-985] Force postgrest to wait for diesel

doc/doc-site/docs/security.md
Update docs for multisig account description
=> [ECO-1015] Update multisig account docs

README.md, scripts.sh
Simplify repo README, note that scripts.sh isn't actively maintainted
=> [ECO-446] Clean up README, scripts

doc/doc-site/docs/security.md
Link to ImmuneFi program on docs site security page
=> [ECO-1128] Link to ImmuneFi program on docs site

src/rust/dbv2/migrations/2024-01-09-160715_price_to_nominal/down.sql, src/rust/dbv2/migrations/2024-01-09-160715_price_to_nominal/up.sql
This PR adds a PostgreSQL function to convert price to a nominal amount.
It is supposed to be later used in Grafana.
=> [ECO-1121] add function to convert price to nominal

doc/doc-site/docs/off-chain/dss/changelog.md
Incorporate a fix for the processor issue that led to a testnet crash, and update the changelog
=> [ECO-1274] Incoporate fixed processor, bump changelog

doc/doc-site/docs/off-chain/dss/changelog.md
Bump DSS stable branch for v1.6.1 release
=> [ECO-1270] Bump stable DSS release for v1.6.1

src/rust/dbv2/migrations/2024-03-08-140100_defillama_fees_24h/down.sql, src/rust/dbv2/migrations/2024-03-08-140100_defillama_fees_24h/up.sql
Add an endpoint for 24h fees to facilitate DefiLlama integration.
=> [ECO-1335] add 24h fees

src/rust/dbv2/migrations/2024-03-12-180959_remove_unused_indices/down.sql, src/rust/dbv2/migrations/2024-03-12-180959_remove_unused_indices/up.sql
This PR removes unused indices and frees up GBs of space.
=> [ECO-1354] remove unused indices

src/rust/dbv2/migrations/2024-03-14-145448_cumulative_fees/down.sql, src/rust/dbv2/migrations/2024-03-14-145448_cumulative_fees/up.sql
This is needed for DefiLlama and was somehow forgotten about.
=> [ECO-1379] add cumulative fees

src/terraform/dss-ci-cd/scripts/hot-upgrade.sh
Update the hot upgrade script to rebuild the new custom MQTT binary
=> [ECO-1425] Include MQTT rebuild in hot upgrade script

src/docker/processor/start.sh, src/rust/Cargo.lock, src/rust/Cargo.toml, src/rust/aggregator/Cargo.toml, src/rust/dbv2/migrations/2024-03-15-155536_update_processor_status/down.sql, src/rust/dbv2/migrations/2024-03-15-155536_update_processor_status/up.sql
Update Cargo configs and an SQL definition per recent changes to processor
=> [ECO-1347] Update workspace to work with new upstream changes for the processor

doc/doc-site/docs/security.md
Update the security docs page per audit of #691
=> [ECO-1226] Bump security page for recent audit

src/rust/aggregator/src/dbtypes.rs, src/rust/aggregator/src/pipelines/user_balances.rs
Remove dead code from aggregator
=> [ECO-809] remove dead code

doc/doc-site/docs/integrators/reference-frontend.md
Link to the Figma template for the reference frontend
=> [ECO-1487] Add figma file link

src/docker/compose.dss-core.yaml, src/rust/Cargo.lock, src/rust/Cargo.toml, src/rust/aggregator/Cargo.toml, src/rust/aggregator/src/main.rs, src/rust/aggregator/src/pipelines/refresh_materialized_view.rs, src/rust/dbv2/migrations/2024-03-24-115433_drop_old_triggers/down.sql, src/rust/dbv2/migrations/2024-03-24-115433_drop_old_triggers/up.sql
This PR adds improved logging for the aggregator to better debug in case of crashes.
=> [ECO-1462] improve aggregator logging

src/docker/aggregator/Dockerfile, src/docker/processor/Dockerfile
Handle the experimental tokio build in aggregator/processor dockerfiles
=> [ECO-1491] add tokio env var to dockerfiles to fix build

doc/doc-site/docs/integrators/reference-frontend.md
This also makes the docs consistent with the frontend `README.md`
=> [ECO-1512] Update the docs site docs to mention the new integrator fee store environment variable for the reference frontend

.github/workflows/PULL_REQUEST_TEMPLATE.md
=> [Add PR template] Add pull request template

doc/doc-site/docs/off-chain/dss/changelog.md
Update DSS v2.1.0 changelog for incorporation of upstream changes
Local docs serve
=> [ECO-1594] Include upstream incorporation in DSS changelog

doc/doc-site/docs/off-chain/dss/changelog.md, src/rust/dbv2/migrations/2024-05-08-124631_fix_nominal_2/down.sql, src/rust/dbv2/migrations/2024-05-08-124631_fix_nominal_2/up.sql
This PR fixes a function used in `api.tickers` that would return a bad price.
Run DSS and ensure `price` column in `api.tickers` is correct.
=> [ECO-1652] fix last price in tickers

src/rust/dbv2/migrations/2024-05-12-144131_fix_tick_size/down.sql, src/rust/dbv2/migrations/2024-05-12-144131_fix_tick_size/up.sql
Fix some tick size calculations.
=> [ECO-1662] fix tick size calculations

doc/doc-site/docs/off-chain/dss/changelog.md
=> [ECO-1604] update changelog for DSS v2.2.0-rc.1

doc/doc-site/docs/off-chain/dss/changelog.md, src/docker/processor/Dockerfile
Incorporate processor updates for v1.12.0 upstream release
=> [ECO-1723] update processor for v1.12.0 upstream release

doc/doc-site/docs/off-chain/dss/changelog.md
This PR updates the changelog for the release of DSS v2.2.0.
=> [ECO-1761] update changelog for DSS release v2.2.0

doc/doc-site/docs/off-chain/dss/changelog.md
This PR updates the DSS version for the changelog.
=> [ECO-1865] update changelog

doc/doc-site/docs/off-chain/dss/changelog.md
This PR updates the version in the DSS changelog in preparation for the v2.4.0-rc.2 release.
=> [ECO-2088] Update version in changelog

src/rust/dbv2/migrations/2024-09-11-144757_optimize_querying_orders_by_user/down.sql, src/rust/dbv2/migrations/2024-09-11-144757_optimize_querying_orders_by_user/up.sql
This PR adds an index to query orders by market id and user.
=> [ECO-2122] Add DSS index on orders by market ID and user

doc/doc-site/docs/off-chain/dss/changelog.md
This PR updates the links in the changelog for the release of v2.5.0.
=> [ECO-2230] Update changelog
